spring.application.name=SignVault
spring.jpa.open-in-view=false
server.port=${PORT:8080}
server.forward-headers-strategy=framework
#spring.profiles.active=local

#------------------MySQL Database----------------
#spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------ MySQL Database ------------------
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:defaultdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#------------------JPA / Hibernate---------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#------------------Flyway---------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#------------------JWT----------------------------
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

#------------------Google OAuth2----------------
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#------------------Email(Gmail SMTP)--------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.enable=true

#-------------------Cloudinary-----------------------
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#-------------------Twilio-----------------------------
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

#--------------------File Upload-----------------------
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#--------------------Actuator--------------------------
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#-------------------Logging___________________________
logging.level.com.harshalkhade.signvault=DEBUG
logging.level.org.springframework.security=DEBUG

#-------------------CORS--------------------------------
allowed.origins=${ALLOWED_ORIGINS}